[package]
name = "SvgHandler"
version = "0.0.1"

[addresses]
StarcoinFramework = "0x1"
SvgHandler = "0x1168dd67ac004b9b1f3088fbe351819c"
[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin.git", subdir="vm/stdlib", rev="3e895169a8f8dd883277050bb90645c52a370cee"}