[package]
name = "SVGNFT"
version = "0.0.1"

[addresses]
StarcoinFramework = "0x1"
SNFT = "0x19a1aafcd6f427c97c858a76173acc4c"
[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin.git", subdir="vm/stdlib", rev="3e895169a8f8dd883277050bb90645c52a370cee"}

SvgHandler = { local = "../svg-handler"}